#!/bin/bash
set -e

PROJECT_NAME="privacy_preserving_federated_learning"

activate_venv () {
  SWEEP_NAME="$1"

  if [[ "$SWEEP_NAME" == *dp || "$SWEEP_NAME" == *_centralized* ]]; then
    echo "[ENV] Using DP environment (venv_dp) for sweep: $SWEEP_NAME"
    source venv_dp/bin/activate
  else
    echo "[ENV] Using standard environment (venv) for sweep: $SWEEP_NAME"
    source venv/bin/activate
  fi

  python -c "import sys; print('[ENV] Python:', sys.executable)"
}

run_sweep () {
  SWEEP_NAME="$1"
  # optional 2nd arg: config directory (defaults to config/). Redo sweeps live in
  # config/config_redo, so they pass that dir explicitly.
  CONFIG_DIR="${2:-config}"
  CONFIG_PATH="$CONFIG_DIR/$SWEEP_NAME.yaml"

  echo "=================================================="
  echo "[INFO] Creating sweep for: $SWEEP_NAME"
  echo "[INFO] Config: $CONFIG_PATH"
  echo "=================================================="

  if [ ! -f "$CONFIG_PATH" ]; then
    echo "[ERROR] Config not found: $CONFIG_PATH"
    exit 1
  fi

  # Activate correct environment
  deactivate >/dev/null 2>&1 || true
  activate_venv "$SWEEP_NAME"

  # Create sweep
  OUTPUT=$(wandb sweep \
    --project "$PROJECT_NAME" \
    --name "$SWEEP_NAME" \
    "$CONFIG_PATH" 2>&1)

  echo "[DEBUG] wandb sweep output:"
  echo "$OUTPUT"

  # Extract sweep ID
  SWEEP_ID=$(echo "$OUTPUT" | grep -oE '[^ ]+/[^ ]+/[a-zA-Z0-9]{8}' | tail -n1)

  if [ -z "$SWEEP_ID" ]; then
    echo "[ERROR] Failed to extract sweep ID."
    exit 1
  fi

  echo "[INFO] Launching agent for sweep ID: $SWEEP_ID"
  wandb agent "$SWEEP_ID"
}

# ==================================================
# BODY SIGNAL OF SMOKING
# ==================================================
#run_sweep "smoking_fl"
#run_sweep "smoking_fl_dp_central"
#run_sweep "smoking_fl_dp_local"

# ==================================================
# CIFAR-10
# ==================================================
run_sweep "cifar_fl_dp_central"
run_sweep "cifar_fl"
run_sweep "cifar_fl_dp_local"

# ==================================================
# NETWORK MONITORING
# ==================================================
#run_sweep "network_fl"
#run_sweep "network_fl_dp_central"
#run_sweep "network_fl_dp_local"

# ==================================================
# HOUSEHOLD POWER  (new time-series benchmark, R2.6)
# ==================================================
#run_sweep "household_fl"
#run_sweep "household_fl_dp_central"
#run_sweep "household_fl_dp_local"

# ==================================================
# REDO OF FAILED RUNS
# Generated by generate_redo_configs.py into config/config_redo/.
# The 2nd arg points run_sweep at that subfolder. Only uncomment the groups the
# generator actually wrote a file for (it only emits YAMLs for dataset/mechanism
# pairs that had failures).
# ==================================================

# --- Smoking ---
#run_sweep "smoking_fl"            "config/config_redo"
#run_sweep "smoking_fl_dp_central" "config/config_redo"
#run_sweep "smoking_fl_dp_local"   "config/config_redo"

# --- CIFAR-10 ---
#run_sweep "cifar_fl"             "config/config_redo"
#run_sweep "cifar_fl_dp_central"  "config/config_redo"
#run_sweep "cifar_fl_dp_local"    "config/config_redo"

# --- Network Monitoring ---
#run_sweep "network_fl"            "config/config_redo"
#run_sweep "network_fl_dp_central" "config/config_redo"
#run_sweep "network_fl_dp_local"   "config/config_redo"

# --- Household Power ---
#run_sweep "household_fl"            "config/config_redo"
#run_sweep "household_fl_dp_central" "config/config_redo"
#run_sweep "household_fl_dp_local"   "config/config_redo"
