program: run.sh
project: privacy_preserving_federated_learning
method: grid

parameters:
  dataset:
    value: "cifar10"
  aggregation_type:
    # values: ["regular", "secure"]
    value: "regular"
  dp:
    value: False
  n_clients:
    values: [3, 6, 10]
  partition_type:
    # values: ["iid", "noniid"]
    value: "iid"
  learning_rate:
    value: 0.0005
  batch_size:
    value: 16
  epochs:
    value: 50
  l2_norm_clip:
    # values: [0.1, 1, 5, 10]
    values: [1, 5]

command:
  - ${env}
  - bash
  - ${program}
  - ${args}
