program: run.sh
project: privacy_preserving_federated_learning
method: grid

parameters:
  dataset:
    value: "network_monitoring"
  partition_type:
    value: "centralized"
  no_fl:
    value: True
  dp:
    value: True
  noise_multiplier:
    values: [0.01, 0.1, 1, 10]
  l2_norm_clip:
    values: [0.1, 1, 5, 10]
  learning_rate:
    values: [0.01, 0.001, 0.0001]
  batch_size:
    value: 128
  epochs:
    value: 30
  

command:
  - ${env}
  - bash
  - ${program}
  - ${args}