program: run.sh
project: privacy_preserving_federated_learning
method: grid

parameters:
  dataset:
    value: "network_monitoring"
  aggregation_type:
    value: "regular"
  dp:
    value: True
  local:
    value: True
  epsilon:
    values: [1, 3, 10, 30, 100, 300]
  l2_norm_clip:
    values: [1, 5]
  partition_type:
    value: "iid"
  n_clients:
    values: [3, 6, 10]
  learning_rate:
    value: 0.01
  batch_size:
    value: 128
  epochs:
    value: 30
  seed:
    values: [0, 1, 2, 3, 4]

command:
  - ${env}
  - bash
  - ${program}
  - ${args}
