program: run.sh
project: privacy_preserving_federated_learning
method: grid

parameters:
  dataset:
    value: "body_signal_of_smoking"
  aggregation_type:
    value: "regular"
  dp:
    value: True
  local:
    value: False
  clipping:
    value: "server"
  noise_multiplier:
    values: [0.7, 0.47, 1.41] #5, 3, 1 epsilon
  l2_norm_clip:
    values: [1, 5]
  partition_type:
    value: "iid"
  n_clients:
    values: [3, 6, 10]
  learning_rate:
    value: 0.001
  batch_size:
    value: 128
  epochs:
    value: 30
  

command:
  - ${env}
  - bash
  - ${program}
  - ${args}